Manually mock service_catalog in stub_keystoneclient
MockObject.__init__ ignores properties, fixes:

FAIL: test_get_default_role (openstack_dashboard.test.api_tests.keystone_tests.RoleAPITests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/openstack-dashboard-test/openstack_dashboard/test/api_tests/keystone_tests.py", line 78, in test_get_default_role
    keystoneclient = self.stub_keystoneclient()
  File "/var/lib/openstack-dashboard-test/openstack_dashboard/test/helpers.py", line 287, in stub_keystoneclient
    self.keystoneclient = self.mox.CreateMock(keystone_client.Client)
  File "/usr/lib64/python2.6/site-packages/mox.py", line 258, in CreateMock
    new_mock = MockObject(class_to_mock, attrs=attrs)
  File "/usr/lib64/python2.6/site-packages/mox.py", line 556, in __init__
    attr = getattr(class_to_mock, method)
  File "/usr/lib64/python2.6/site-packages/mox.py", line 608, in __getattr__
    raise UnknownMethodCallError(name)
UnknownMethodCallError: Method called is not a member of the object: service_catalog
>>  raise UnknownMethodCallError('service_catalog')

(cherry picked from commit 82bdecb117877bc0bd1bbd553fbd40d04cbe9078)

Temporary change the django_openstack_auth requirement

The new django_openstack_auth version causes gate job issues like:
http://logs.openstack.org/33618/5/gate/gate-tempest-devstack-vm-full/29950/console.html

Temporary disabling the 1.1.0 version.

(from commit 2ffe032dbf21757bd574dedffa3cd3f6927bbfe3)

Mock some more keystoneclient.Client properties for mox

Fixes LP bug 1196823

Change-Id: I9b0c56eda95ee83cf56a28f2f1b7316ad2592fa2
(cherry picked from commit 2a6d669443b817ced3a98f5bc60a066298b6e40e)