Fix popup error when volume service disabled
In an enviroment, where cinder is disabled, I'm getting error popups
when trying to 'launch instance':
Error: Unable to retrieve list of volumes.
Error: Unable to retrieve list of volume snapshots.
So we need to make sure whether the volume service exists when
calling the cinder api in the launch instance workflow.

Closes-bug: #1394900

Conflicts:
	openstack_dashboard/dashboards/project/instances/workflows/create_instance.py

Change-Id: I6f745f7f95272eb87b6d867d76d7726c7eb5bb24
(cherry picked from commit 6a7b95ad8e33a01f55ae857ca5a0fad496dde4da)