Fix maximum recursion depth error when generating documentation
Troubleshooting an issue with Senlin documentation,

> RecursionError: maximum recursion depth exceeded in __instancecheck__

it turns out that attrs['base_options'] creates a recursive reference
when no base classes have 'base_options'.
This happens when BaseAction is created.

Closes-Bug: #1955773
Change-Id: I2724f07339134b3e06b7ea925939bf7072162106
(cherry picked from commit b8cc0043d46318c7e11952109450587bee9567ab)