Handle situation when endpoint deleted
when the cinder services exist but endpoint deleted, accessing
to /project/access_and_security will cause an error:
IndexError: list index out of range

Change-Id: Iad7f72cd5247f33245f25a8092c40a4d3a04cef9
Partial-Bug: #1394900
(cherry picked from commit 7985cfce77975d25ec6615b94f98ad920e727f93)